name: Version or Publish
on:
  push:
    branches:
      - main
concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
  changesets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Build
        run: pnpm build
      - name: Create Release Pull Request or Publish
        id: changesets
        uses: ./
        with:
          version: pnpm bump
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
